In [2]:
import numpy as np
import numpy.random as rand

In [ ]:
#Assume all input factors (parameters) are normalized to [0,p] uniform distribution, where p - number of levels
n_params = 10

#Number of levels
p = 4 
if p%2 != 0:
    print("Even number of levels is better")
    
#Stepsize as recommended in [2007] Campologno - An effective screening design...
delta = p/(2*(p-1))

#Generate one trajectory
def gen_trajectory(n,p):
    #n - number of factors, p - number of levels
    #Choose start value
    xs = rand.randint(1,p,n)
    #Create a trajectory
    tr = rand.randint(1,n,n+1)
    x_signs = rand.choice([-1,1],n+1)
    return 
    
n_tr = 10
for i in range(n_tr):
    tr = gen_trajectory

In [17]:
rand.randint(1,4,3)

array([3, 2, 2])

In [20]:
p = 4
n = 10
xs = rand.randint(1,p,n)
#Create a trajectory
tr = rand.randint(1,n,n+1)
x_signs = rand.choice([-1,1],n+1)

In [21]:
xs

array([3, 2, 2, 1, 1, 2, 1, 2, 1, 3])

In [22]:
tr

array([9, 7, 3, 2, 5, 4, 2, 6, 4, 6, 6])

In [23]:
x_signs


array([ 1,  1, -1, -1, -1,  1,  1,  1, -1,  1, -1])

In [26]:
nn = np.arange(n+1)

In [29]:
tr >= nn.transpose()

array([ True,  True,  True, False,  True, False, False, False, False,
       False, False])